config/routes.rb
Rails.application.routes.draw do
  get 'onlines/index'
  get 'sessions/new'
  get 'user/new'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/password_reset', to: 'password_resets#form_email', as: 'password_reset'
  post '/password_reset', to: 'password_resets#create', as: 'password_resets_new'
  get '/password_reset/:id/edit', to: 'password_resets#edit', as: 'edit_password_reset'
  patch '/password_reset/:id/edit', to: 'password_resets#update', as: 'update_password_reset'
  resources :users
  resources :account_activations, only: [:edit]
  resources :rooms, only: [:show, :create, :index]
  resources :onlines
  resources :search_users, only: [:create]

  resources :messages, only: [:create, :update, :destroy]

  mount ActionCable.server => '/cable'
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :current_user, only: ["edit", "update"]
  before_action :auth, only: ["edit", "update"]
  before_action :check_expration, only: ["edit", "update"]

  def form_email
    @user = User.new
  end

  def create
    @user = User.find_by email: email_params[:email].downcase
    if @user && @user.save_password_reset
      @user.send_mail_user_password_reset_model
      flash[:info] = "Please check your email to reset password your account."
      redirect_to root_url
    else
      flash[:danger] = "This email is not exsit!"
      render 'form_email'
    end
  end

  def edit
  end

  def update
    if params[:user][:password].empty?
      @user.errors.add(:password, "can't be empty!")
      render 'edit'
    elsif @user.update_attributes(password_params)
      log_in @user
      redirect_to @user
    else 
      render 'edit'
    end
  end

  private
  def check_expration
    if @user.password_reset_expired?
      flash[:danger] = "Password reset has expired!"
      redirect_to password_resets_new_path
    end
  end

  def auth
     unless(@user && @user.authenticated?(:password_reset, params[:id]))
      render 'activation_error'
     end
  end

  def current_user
    @user = User.find_by email: params[:email]
  end

  def email_params
    params.require(:password_reset).permit(:email)
  end

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/activation_error.html.erb
<h1>Reset password fail</h1>

app/views/password_resets/edit.html.erb
<h1>Reset your password</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: update_password_reset_path(params[:id], email: @user.email)) do |f| %>
      <%= render 'shared/error_messages', object: @user %>
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Update", class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/password_resets/form_email.html.erb
<% provide :title, "Reset password" %>

<h1>Reset your password</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <%= form_for(:password_reset, url: password_resets_new_path) do |f| %>
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>

    <%= f.submit "Reset", class: "btn btn-primary" %>
  <% end %>
  </div>
</div>