config/routes.rb
Rails.application.routes.draw do
  get 'onlines/index'
  get 'sessions/new'
  get 'user/new'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/password_reset', to: 'password_resets#form_email', as: 'password_reset'
  post '/password_reset', to: 'password_resets#create', as: 'password_resets_new'
  get '/password_reset/:id/edit', to: 'password_resets#edit', as: 'edit_password_reset'
  patch '/password_reset/:id/edit', to: 'password_resets#update', as: 'update_password_reset'
  resources :users
  resources :account_activations, only: [:edit]
  resources :rooms, only: [:show, :create, :index]
  resources :onlines
  resources :search_users, only: [:create]

  resources :messages, only: [:create, :update, :destroy]

  mount ActionCable.server => '/cable'
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages 
  has_many :room_users 
  has_many :users, through: :room_users
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :logged_in_user
  before_action :all_users
  before_action :check_mems_room, only: [:show]
 
  def index
    @rooms = current_user.rooms

  end

  def show
    @message = Message.new
    @room = Room.find_by id: params[:id]
    @messages = @room.messages
  end

  def create
  end


private
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in"
      redirect_to login_url
    end
  end

  def all_users
    @users = User.is_online
  end

  def check_mems_room
    @room = Room.find_by id: params[:id] 
    redirect_to rooms_url if !@room.users.include?(current_user)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/index.html.erb
<div class="chat-status">
  <div class="rooms">
    <h1>Rooms</h1>
    <ul>
      <% @rooms.each do |room| %>
        <li>
          <%= link_to room.name, room_path(room) %>
        </li>
      <% end %>
    </ul>
  </div>
<div class="status">
  <%= render template: "onlines/index" %>
</div>
</div>

app/views/rooms/show.html.erb
<div class="chat-status">
  <div class="chat">
    <h1>Chat</h1>
    <div class="search">
      <%= form_for(:user, url: search_users_path) do |f| %>
        <%= f.hidden_field :room_id, value: params[:id] %>
        <%= f.text_field :user_name %>
      <% end %>
    </div>
    <div id="messages" data-room_id="<%= @room.id %>">
      <%= render @messages if !@messages.nil? %>
    </div>
    <div class="form">
      <%= render 'messages/message_form' %>
    </div>
  </div>
  <div class="status">
    <%= render template: 'onlines/index' %>
  </div>
</div>